### ISSUE TITLE
Map for external keyboard only

### ISSUE THREAD

**Issue by scottgrayson** [koekeishiya/khd#13]
My laptop and external keyboard have alt/cmd in opposite places. I would like to swap alt/cmd on my external keyboard so the layout is matched. I could edit my config and reload whenever i switch keyboards, but is there a better way? Can this be done with the Mode feature?

**Comment by koekeishiya** [comment]
Khd isn't really meant for key-remapping, but rather keybindings.

This has the effect that you can keybind any key-combination to simulate another key-combination.
This can be used to effectively perform a "key-remap".

Because a modifier is a flag which in turn modifies a state of some other input event, you will not be able to remap alt to cmd, and cmd to alt (and so on) with Khd.

Now, it isn't impossible to implement support for this in Khd, but for now remapping modifiers is not possible.

**Comment by koekeishiya** [comment]
After some thinking, I find this to be out of scope for Khd.
The reason for this is that (to my knowledge), we are not able to tell which keyboard emitted the event.

This requires hooking input at a lower level. 
[Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements) should be able to this, although I do not yet know how far along the rewrite has come.

**Comment by dominiklohmann** [comment]
Current version of macOS Sierra can do this natively, and you can configure it per keyboard.
<img width="780" alt="screen shot 2017-01-16 at 17 08 21" src="https://cloud.githubusercontent.com/assets/4488655/21990271/705c130c-dc0e-11e6-902a-96fc4bf31cf8.png">
