### ISSUE TITLE
Help with Setting up a Config File

### ISSUE THREAD

**Issue by austin-guevara** [koekeishiya/khd#25]
Hey all,

Sorry to be a bother here – I'm having a tough time following the example config file. I'm not ashamed to admit that I'm not always the most savvy when it comes to these things.

I'm trying to setup keybindings for kwm that are much like i3, wherein left alt would be my "mod" key. Could someone show me the fundamentals if I wanted to create keybindings such as the following:

**Shift focus up**
`left alt + up arrow`

**Shift focus right**
`left alt + right arrow`

**Shift focus down**
`left alt + down arrow`

**Shift focus left**
`left alt + left arrow`

**Move window up**
`left alt + shift + up arrow`

**Move window right**
`left alt + shift + right arrow`

**Move window down**
`left alt + shift + down arrow`

**Move window left**
`left alt + shift + left arrow`

**Open new terminal window**
`left alt + enter`

These are the most important keybindings I want to create. If I know how to write these ones, it will be easy to write any additional that I may want to add.

Thank you!

**Comment by koekeishiya** [comment]
shift focus
`lalt - up : kwmc window -f north`
`lalt - right : kwmc window -f east`
`lalt - down : kwmc window -f south`
`lalt - left : kwmc window -f west`

move window
`lalt + shift - up : kwmc window -m north`
`lalt + shift - right : kwmc window -m east`
`lalt + shift - down : kwmc window -m south`
`lalt + shift - left : kwmc window -m west`

Open new terminal window
`lalt - return : open -na /Applications/iTerm2.app`  (change path to Terminal.app or whatever terminal program you use, I personally use an applescript to create a new iterm window rather than starting a new application instance)

**Comment by austin-guevara** [comment]
Wow, thank you for the in-depth response. This is extremely helpful, thank you so much!

Will reference #9 for troubleshooting. Thanks!
