### ISSUE TITLE
Caps Lock as modifier key

### ISSUE THREAD

**Issue by a9udn9u** [koekeishiya/khd#49]
Is there a way to use caps lock as a modifier key?

Already tried to combine caps lock keycode with other literals but looks like that's not allowed.

Thanks.

**Comment by chrishoage** [comment]
You can use something like Karabiner-Elements to rebind caps lock to another key, then bind khd to that key. Or, you can use OS X settings to rebind capslock to ctrl / esc (I have it bound to ctrl)

**Comment by a9udn9u** [comment]
Sounds like a good workaround, thanks!

However I still prefer to be able to use caps lock as a separate modifier key, otherwise I can't bind `caps lock + literal` and `ctrl + literal` to different commands.

**Comment by matthewdias** [comment]
you can if you map caps to right control, for example. that's what i do. obviously you'll need to pick a mod that you don't have/don't use.

**Comment by koekeishiya** [comment]
Khd does not track caps lock in any way. 
Your options are more or less what has already been mentioned.

Considering this resolved.

**Comment by thomasjachmann** [comment]
@koekeishiya I came across this ticket because on Sierra, I cannot achieve what I did with Seil/Karabiner before with either khd or Karabiner-Elements alone. Out of curiosity: Is handling caps lock significantly different or more difficult than handling the other modifier keys? Could it be implemented easily?

Handling keyboard events is rather time critical to me (I experienced quite some lag sometimes due to keyboard customizations in the past), so I'd really like not having to use several tools to achieve something, especially if one tool is in the event handler chain just to handle a single key. Maybe you can reconsider implementing caps lock handling.

**Comment by koekeishiya** [comment]
> Out of curiosity: Is handling caps lock significantly different or more difficult than handling the other modifier keys? Could it be implemented easily?

IIRC, when caps-lock is pressed, we receive a `CGEventFlagsChanged` event.
A flag is also set in the `CGEventFlags` that indicates if caps-lock is on or off.

Having caps-lock perform some command when pressed, alone, would probably be quite easy
to implement. Having caps-lock perform as a modifier along other modifiers and keys might
be tricky to do, I haven't really thought enough about it to make a proper judgement.

> Maybe you can reconsider implementing caps lock handling.
I've created issue #55 to allow this to be tracked more easily, 
no promises that this is going to happen though.
