### ISSUE TITLE
Khd cant start daemon

### ISSUE THREAD

**Issue by OrBaruk** [koekeishiya/khd#53]
Hi,

After updating my osx _khd_ stopped working.

When trying to start the _khd_ manually it prints the following message.

```
Khd: Could not start daemon! Terminating.
```

The updates done by AppStore where the following:
- Safari version 10.0.3
- Security Update 2016-003 Supplemental Update version 10.11.6
- ITunes version 12.5.5

I think it is the second one that caused the issue.

**khd version:** 1.2.0 installed with homebrew
**System version:** El Captain version 10.11.6 (15G1217)

**Comment by JackyChiu** [comment]
Also having the same issue +1

**Comment by chrishoage** [comment]
what does `/tmp/khd.out` and `/tmp/khd.err` say? 

I just updated to 1.2.0 and have that security update installed and it worked. [

@koekeishiya I did have to accept khd into my Accessibility policies again. I think something is up with the code signing certificate

**Comment by koekeishiya** [comment]
> I did have to accept khd into my Accessibility policies again. I think something is up with the code signing certificate

Hm weird. Thanks for letting me know, will investigate further.

This is likely to be the problem for the people above as well.

The following steps should be enough to solve the problem:
```
remove existing accessibility access from khd.
add khd to accessibility again

# note that the brew service must be restarted after the permissions have been given
brew services stop khd
brew services start khd

if restarting brew is not enough, a system reboot may be necessary
```

**Comment by OrBaruk** [comment]
Can confirm that the system reboot solved the issue, thanks!

**Comment by JackyChiu** [comment]
Fixes for me as well, thanks!

**Comment by braham-snyder** [comment]
Since the following underlying cause is sort of only mentioned in passing in [another issue](https://github.com/koekeishiya/khd/issues/17):

I ran into this `Khd: Could not start daemon! Terminating.` error, not fixable by restarting the brew service, because port 3021 was blocked. This cause can be confirmed* with `lsof -i :3021`, and fixed by closing the applications printed, reloading ~/.khdrc and fixing any errors, and then restarting the brew service.

On a related note, whenever I launch `emacsclient` through khd, it listens on port 3021, despite my setting Emacs' `server-port` variable to 3022. Anyone happen to know how to circumvent that?

* At one point, I thought `lsof -i :3021` was missing applications that `lsof -n -i4TCP:3021` was not, but I'm not able to reproduce that now.
