### ISSUE TITLE
no [at] sign because of khd

### ISSUE THREAD

**Issue by prankousky** [koekeishiya/khd#88]
hi,

i am using **khd** in combination with **chunkwm** on OSX sierra. it works fine, however, it seems to mess up keyboard shortcuts. i am not able to type `at` (command + L) anymore. i guess this is due to the example config, which has this shortcut do something else.

i have tried stopping khd, which did not seem to work. **activity monitor** was not able to stop the process; `pkill khd` did nothing. when i `top | grep khd` and then kill the process number, it respawns with a new process number.

i did install both services via brew btw.
can somebody please help me out? i am just getting used to alternative window managers; it is a lot of fun. but i need to be able to use the alt key for the things i am used to.. 

thanks in advance :)

**Comment by koekeishiya** [comment]
Brew runs *Khd* as a service. To stop / quit *Khd*, you need to also stop the Brew service.
This can be done by running the following command from a terminal: `brew services stop khd`

You can manually start *Khd* by running it from terminal instead of having it be managed by the Brew service. This is usually how I do it (by running it manually inside a tmux session).

**Comment by prankousky** [comment]
awesome, thank you!

**Comment by HobbinHood** [comment]
Hi,

ran into this as well.
For me, on a german layout, it's actually `alt+l` for at symbol and `alt+e` for the euro symbol.

Also navigating and at the same time selecting text (alt+shift+<left-/rightarrowkey> for selecting words in direction) in gui applications conflicts with the needed modifier keys, but that's not major for me.

Problem is, I really like the vim-esque focus navigation and window movement shortcuts and don't really want to mess this up.

I was thinking about using `ralt` or `lalt` for all the modifier keys in khdrc. But then again it messes with touch typing (10 finger system) for either smybols accessed via alt modifier (at, euro, etc.) or for khdrc bindings for chunkwm control.
I know, I can't have it all x,D

Are there any other creative ideas for a better solution?

PS: how in the world I never found kwm or more recently chunkwm, while searching for a tiling wm solution for my mac. But I'm very glad I found your project now. It's pure and utter bliss \o/

**Comment by koekeishiya** [comment]
Many people use Karabiner-Elements to make caps-lock into "hyper", which is the modifier combination cmd + shift + alt + ctrl and use this for all custom shortcuts (e.g: chunkwm).

I personally only use a few of the system shortcuts  so I rarely get collisions anyway. A possible sokution is the FN modifier for keyboards that support it, but there were some issues the last time I tried that.

**Comment by HobbinHood** [comment]
Thanks for the hints regarding Karabiner-Elements and the idea about the fn-key.

With hyper I could cover some of the chunkwm commands in khdrc, and I'd like to revolve the whole khdrc around hyper then. But I wouldn't be able to use hyper with alternate commands (increase and decrease size comes to mind), since it already uses shift, right? Or is it possible to have left and right modifier keys be a requirement?

Now I'm curious: How do you type symbols like (at) and other things accessible via alt/option+<letter key> with the default khdrc from chunkwm?

**Comment by koekeishiya** [comment]
The asterisk (*) above the right shift-key is @ in my locale (norwegian keyboard layout) by default.
